// Data generation
var mapper = function ($1, $2) {
  var struct = {
    test: $1,
    answers: _.map($2.split(','), function (s) { return s.trim(); })
  };
  return [$1,
    $2,
    JSON.stringify(struct) + ","];
};

var TypingData = {
  "Latin/Unit1/Stage1": [
    { "test": "atrium", "answers": ["reception hall", "atrium"] },
    { "test": "canis", "answers": ["dog"] },
    { "test": "coquus", "answers": ["cook"] },
    { "test": "cubiculum", "answers": ["bedroom"] },
    { "test": "culina", "answers": ["kitchen"] },
    { "test": "est", "answers": ["is"] },
    { "test": "filius", "answers": ["son"] },
    { "test": "hortus", "answers": ["garden"] },
    { "test": "in", "answers": ["in", "on"] },
    { "test": "laborat", "answers": ["is working", "works"] },
    { "test": "mater", "answers": ["mother"] },
    { "test": "pater", "answers": ["father"] },
    { "test": "sedet", "answers": ["sits", "is sitting"] },
    { "test": "servus", "answers": ["slave", "servant"] },
    { "test": "tablinium", "answers": ["study"] },
    { "test": "triclinium", "answers": ["dining room"] },
    { "test": "via", "answers": ["street"] }
  ],
  "Latin/Unit1/Stage2": [
    { "test": "amicus", "answers": ["friend"] },
    { "test": "ancilla", "answers": ["slave girl", "slave woman"] },
    { "test": "cena", "answers": ["dinner", "supper"] },
    { "test": "cibus", "answers": ["food"] },
    { "test": "dominus", "answers": ["master"] },
    { "test": "dormit", "answers": ["sleeps"] },
    { "test": "gustat", "answers": ["tastes", "eats"] },
    { "test": "intrat", "answers": ["enters"] },
    { "test": "laetus", "answers": ["happy"] },
    { "test": "laudat", "answers": ["praises", "praise"] },
    { "test": "mensa", "answers": ["table"] },
    { "test": "mercator", "answers": ["merchant"] },
    { "test": "quoque", "answers": ["also", "too"] },
    { "test": "salutat", "answers": ["greets", "salutes"] },
    { "test": "toga", "answers": ["toga"] },
    { "test": "tunica", "answers": ["tunic"] },
  ],
  "Latin/Unit1/Stage3": [
    { "test": "ad", "answers": ["to"] },
    { "test": "bibit", "answers": ["drinks"] },
    { "test": "circumspectat", "answers": ["looks around"] },
    { "test": "clamat", "answers": ["shouts"] },
    { "test": "ecce", "answers": ["see", "look"] },
    { "test": "et", "answers": ["and"] },
    { "test": "exit", "answers": ["exit", "goes out"] },
    { "test": "exspectat", "answers": ["waits for"] },
    { "test": "forum", "answers": ["forum", "business center"] },
    { "test": "ianua", "answers": ["door"] },
    { "test": "iratus", "answers": ["angry", "mad"] },
    { "test": "leo", "answers": ["lion"] },
    { "test": "magnus", "answers": ["big", "large", "great"] },
    { "test": "navis", "answers": ["ship"] },
    { "test": "non", "answers": ["not", "is not"] },
    { "test": "portat", "answers": ["carries"] },
    { "test": "respondet", "answers": ["responds", "replies"] },
    { "test": "ridet", "answers": ["laughs", "smiles"] },
    { "test": "salve", "answers": ["hi", "hello"] },
    { "test": "surgit", "answers": ["gets up", "rises"] },
    { "test": "taberna", "answers": ["store", "shop", "inn"] },
    { "test": "videt", "answers": ["sees", "looks"] },
    { "test": "villa", "answers": ["house", "village", "farm"] },
    { "test": "vinum", "answers": ["wine", "vinegar"] }
  ],
  "Latin/Unit1/Stage4": [
    { "test": "agit", "answers": ["does"] },
    { "test": "negotium agit", "answers": ["does business"] },
    { "test": "anulus", "answers": ["ring"] },
    { "test": "cera", "answers": ["wax", "wax tablet"] },
    { "test": "coquit", "answers": ["cooks"] },
    { "test": "cur", "answers": ["why"] },
    { "test": "e, ex", "answers": ["out of", "from"] },
    { "test": "ego", "answers": ["I"] },
    { "test": "eheu", "answers": ["alas", "oh dear"] },
    { "test": "habet", "answers": ["has", "had"] },
    { "test": "inquit", "answers": ["says"] },
    { "test": "iudex", "answers": ["judge"] },
    { "test": "mendax", "answers": ["liar"] },
    { "test": "pecunia", "answers": ["money"] },
    { "test": "perterritus", "answers": ["terrified"] },
    { "test": "poeta", "answers": ["poet"] },
    { "test": "quaerit", "answers": ["searches for", "looks for", "searches", "looks"] },
    { "test": "quis", "answers": ["who"] },
    { "test": "reddit", "answers": ["gives back"] },
    { "test": "satis", "answers": ["enough"] },
    { "test": "sed", "answers": ["but"] },
    { "test": "signum", "answers": ["sign", "seal", "signal"] },
    { "test": "tu", "answers": ["you"] },
    { "test": "vendit", "answers": ["sells"] },
    { "test": "vocat", "answers": ["calls"] }
  ],
  "Latin/Unit1/Stage5": [
    { "test": "adest", "answers": ["is here"] },
    { "test": "adsunt", "answers": ["are here"] },
    { "test": "audit", "answers": ["hears", "listens to"] },
    { "test": "clamor", "answers": ["shout", "uproar"] },
    { "test": "contendit", "answers": ["hurries"] },
    { "test": "currit", "answers": ["runs"] },
    { "test": "euge!", "answers": ["hurrah"] },
    { "test": "fabula", "answers": ["play", "show", "story"] },
    { "test": "fabulam agit", "answers": ["acts in a play"] },
    { "test": "femina", "answers": ["woman"] },
    { "test": "hodie", "answers": ["today"] },
    { "test": "iuvenis", "answers": ["young man"] },
    { "test": "meus", "answers": ["my", "mine"] },
    { "test": "multus", "answers": ["much"] },
    { "test": "multi", "answers": ["many"] },
    { "test": "optimus", "answers": ["very good", "excellent", "best"] },
    { "test": "petit", "answers": ["heads for", "attacks", "seeks", "looks for", "searches for"] },
    { "test": "plaudit", "answers": ["applauds", "claps"] },
    { "test": "puella", "answers": ["girl"] },
    { "test": "senex", "answers": ["old man"] },
    { "test": "spectat", "answers": ["looks at", "watches"] },
    { "test": "stat", "answers": ["stands"] },
    { "test": "turba", "answers": ["crowd"] },
    { "test": "ubi", "answers": ["where"] },
    { "test": "urbs", "answers": ["city"] },
    { "test": "venit", "answers": ["comes"] }
  ],
  "Latin/Unit1/Stage6": [
    { "test": "abest", "answers": ["is out", "is absent", "absent"] },
    { "test": "aberat", "answers": ["was out", "was absent"] },
    { "test": "avarus", "answers": ["miser"] },
    { "test": "bonus", "answers": ["good", "wonderful"] },
    { "test": "emit", "answers": ["buys"] },
    { "test": "erat", "answers": ["was out", "was absent"] },
    { "test": "ferociter", "answers": ["fiercly"] },
    { "test": "festinat", "answers": ["hurries"] },
    { "test": "fortis", "answers": ["brave", "strong", "courageous"] },
    { "test": "fur", "answers": ["thief"] },
    { "test": "infans", "answers": ["baby", "child", "infant"] },
    { "test": "intente", "answers": ["intently"] },
    { "test": "libertus", "answers": ["freed man", "ex slave", "ex-slave", "not slave anymore"] },
    { "test": "olim", "answers": ["once", "some time ago", "once upon a time"] },
    { "test": "parvus", "answers": ["small", "little"] },
    { "test": "per", "answers": ["through"] },
    { "test": "postquam", "answers": ["after", "when"] },
    { "test": "pulsat", "answers": ["hits", "punches", "whacks"] },
    { "test": "quod", "answers": ["because"] },
    { "test": "res", "answers": ["thing"] },
    { "test": "scribit", "answers": ["write", "writes", "written"] },
    { "test": "subito", "answers": ["suddenly"] },
    { "test": "superat", "answers": ["overcomes", "overpowers"] },
    { "test": "tum", "answers": ["then"] },
    { "test": "tuus", "answers": ["your", "yours"] },
    { "test": "vituperat", "answers": ["finds fault with", "curses", "tells off"] },
  ],
  "Latin/Unit1/Stage7": [
    { "test": "cenat; cenavit", "answers": ["eats dinner", "dines"] },
    { "test": "centurio", "answers": ["centurion"] },
    { "test": "conspicit; conspexit", "answers": ["catches sight of"] },
    { "test": "cum", "answers": ["with"] },
    { "test": "facit; fecit", "answers": ["makes", "does"] },
    { "test": "heri", "answers": ["yesterday"] },
    { "test": "ingens", "answers": ["huge"] },
    { "test": "intellegit; intellexit", "answers": ["understands", "understood"] },
    { "test": "lacrimat; lacrimavit", "answers": ["cries", "weeps", "cried", "wept"] },
    { "test": "mortuus", "answers": ["dead"] },
    { "test": "narrat; narravit", "answers": ["tells", "relates", "says"] },
    { "test": "necat; necavit", "answers": ["kills"] },
    { "test": "nihil", "answers": ["nothing"] },
    { "test": "omnis", "answers": ["all"] },
    { "test": "parat; paravit", "answers": ["prepares"] },
    { "test": "pestis", "answers": ["pest", "rascal"] },
    { "test": "poculum", "answers": ["cup of wine", "cup for wine", "wine cup"] },
    { "test": "procedit; processit", "answers": ["advances", "proceeds", "proceeds by"] },
    { "test": "prope", "answers": ["near"] },
    { "test": "pulcher", "answers": ["beautiful", "handsome", "pretty"] },
    { "test": "rogat; rogavit", "answers": ["asked", "asks", "questions"] },
    { "test": "tacite", "answers": ["quietly", "silently", "is silent", "is quiet"] },
    { "test": "tamen", "answers": ["however"] },
    { "test": "terret; terruit", "answers": ["frightens", "scares", "terrifies"] },
    { "test": "umbra", "answers": ["ghost", "shadow"] },
    { "test": "valde", "answers": ["much", "very much", "very"] }
  ],
  "Latin/Unit1/Stage8": [
    { "test": "agitat; agitavit", "answers": ["chases", "hunts"] },
    { "test": "consumit; consumpsit", "answers": ["eats", "consumes"] },
    { "test": "ducit; duxit", "answers": ["leads"] },
    { "test": "eum", "answers": ["him"] },
    { "test": "facile", "answers": ["easily"] },
    { "test": "ferox", "answers": ["fierce", "ferocious"] },
    { "test": "gladius", "answers": ["sword"] },
    { "test": "habitat; habitavit", "answers": ["lives"] },
    { "test": "hic", "answers": ["this"] },
    { "test": "ignavus", "answers": ["cowardly", "lazy"] },
    { "test": "incitat; incitavit", "answers": ["urges on", "ecourages", "incites"] },
    { "test": "nuntius", "answers": ["messenger"] },
    { "test": "pes", "answers": ["foot", "paw"] },
    { "test": "portat", "answers": ["gate"] },
    { "test": "postulat; postulavit", "answers": ["demands", "commands"] },
    { "test": "puer", "answers": ["boy"] },
    { "test": "pugnat; pugnavit", "answers": ["fight"] },
    { "test": "recumbit; recubuit", "answers": ["lies down", "reclines"] },
    { "test": "saepe", "answers": ["often"] },
    { "test": "sanguis", "answers": ["blood"] },
    { "test": "silva", "answers": ["woods", "forest"] },
    { "test": "spectaculum", "answers": ["show", "spectacle"] },
    { "test": "statim", "answers": ["at once"] },
    { "test": "totus", "answers": ["whole", "total"] }
  ],
  "Latin/Conjugation": [
    { "test": "how do you translate verb-o", "answers": ["I verb"] },
    { "test": "how do you translate verb-s", "answers": ["you verb"] },
    { "test": "how do you translate verb-t", "answers": ["he verb", "she verb", "it verb"] },
    { "test": "how do you translate verb-mus", "answers": ["we verb"] },
    { "test": "how do you translate verb-tis", "answers": ["you all verb", "ya'll verb"] },
    { "test": "how do you translate verb-nt", "answers": ["they verb", "they all verb"] }
  ],
  Latin2Eng: [
    {
      "test": "canis",
      "answers": ["dog", "hound"]
    },
    {
      "test": "villa",
      "answers": ["town", "farm", "village", "house"]
    },
    {
      "test": "est",
      "answers": ["is"]
    },
    {
      "test": "pater",
      "answers": ["father"]
    },
    {
      "test": "mater",
      "answers": ["mother"]
    },
    {
      "test": "filius",
      "answers": ["son"]
    },
    {
      "test": "servus",
      "answers": ["slave"]
    },
    {
      "test": "coquus",
      "answers": ["cook"]
    },
    {
      "test": "scribit",
      "answers": ["is writing"]
    },
    {
      "test": "sedet",
      "answers": ["is sitting"]
    },
    {
      "test": "bibit",
      "answers": ["is drinking"]
    },
    {
      "test": "laborat",
      "answers": ["is working"]
    },
    {
      "test": "dormit",
      "answers": ["is sleeping"]
    },

  ],
  Chinese2Eng: [
    {
      "test": "山",
      "answers": ["mountain", "hill"]
    }
  ],
  Multiplication: [
    { "test": "2 X 2", "answers": ["4"] },
    { "test": "2 X 3", "answers": ["6"] },
    { "test": "2 X 4", "answers": ["8"] },
    { "test": "2 X 5", "answers": ["10"] },
    { "test": "2 X 6", "answers": ["12"] },
    { "test": "2 X 7", "answers": ["14"] },
    { "test": "2 X 8", "answers": ["16"] },
    { "test": "2 X 9", "answers": ["18"] },
    { "test": "2 X 10", "answers": ["20"] },
    { "test": "2 X 11", "answers": ["22"] },
    { "test": "2 X 12", "answers": ["24"] },
    { "test": "3 X 3", "answers": ["9"] },
    { "test": "3 X 4", "answers": ["12"] },
    { "test": "3 X 5", "answers": ["15"] },
    { "test": "3 X 6", "answers": ["18"] },
    { "test": "3 X 7", "answers": ["21"] },
    { "test": "3 X 8", "answers": ["24"] },
    { "test": "3 X 9", "answers": ["27"] },
    { "test": "3 X 10", "answers": ["30"] },
    { "test": "3 X 11", "answers": ["33"] },
    { "test": "3 X 12", "answers": ["36"] },
    { "test": "4 X 4", "answers": ["16"] },
    { "test": "4 X 5", "answers": ["20"] },
    { "test": "4 X 6", "answers": ["24"] },
    { "test": "4 X 7", "answers": ["28"] },
    { "test": "4 X 8", "answers": ["32"] },
    { "test": "4 X 9", "answers": ["36"] },
    { "test": "4 X 10", "answers": ["40"] },
    { "test": "4 X 11", "answers": ["44"] },
    { "test": "4 X 12", "answers": ["48"] },
    { "test": "5 X 5", "answers": ["25"] },
    { "test": "5 X 6", "answers": ["30"] },
    { "test": "5 X 7", "answers": ["35"] },
    { "test": "5 X 8", "answers": ["40"] },
    { "test": "5 X 9", "answers": ["45"] },
    { "test": "5 X 10", "answers": ["50"] },
    { "test": "5 X 11", "answers": ["55"] },
    { "test": "5 X 12", "answers": ["60"] },
    { "test": "6 X 6", "answers": ["36"] },
    { "test": "6 X 7", "answers": ["42"] },
    { "test": "6 X 8", "answers": ["48"] },
    { "test": "6 X 9", "answers": ["54"] },
    { "test": "6 X 10", "answers": ["60"] },
    { "test": "6 X 11", "answers": ["66"] },
    { "test": "6 X 12", "answers": ["72"] },
    { "test": "7 X 7", "answers": ["49"] },
    { "test": "7 X 8", "answers": ["56"] },
    { "test": "7 X 9", "answers": ["63"] },
    { "test": "7 X 10", "answers": ["70"] },
    { "test": "7 X 11", "answers": ["77"] },
    { "test": "7 X 12", "answers": ["84"] },
    { "test": "8 X 8", "answers": ["64"] },
    { "test": "8 X 9", "answers": ["72"] },
    { "test": "8 X 10", "answers": ["80"] },
    { "test": "8 X 11", "answers": ["88"] },
    { "test": "8 X 12", "answers": ["96"] },
    { "test": "9 X 9", "answers": ["81"] },
    { "test": "9 X 10", "answers": ["90"] },
    { "test": "9 X 11", "answers": ["99"] },
    { "test": "9 X 12", "answers": ["108"] },
    { "test": "10 X 10", "answers": ["100"] },
    { "test": "10 X 11", "answers": ["110"] },
    { "test": "10 X 12", "answers": ["120"] },
    { "test": "11 X 11", "answers": ["121"] },
    { "test": "11 X 12", "answers": ["132"] },
    { "test": "12 X 12", "answers": ["144"] }
  ],
  trig: [
    { "test": "$$sin^{-1}(0)$$", "answers": ["0"] },
    { "test": "$$sin^{-1}({1 \\over 2})$$", "answers": ["30"] },
    { "test": "$$sin^{-1}({1 \\over \\sqrt 2})$$", "answers": ["45"] },
    { "test": "$$sin^{-1}({\\sqrt 3 \\over 2})$$", "answers": ["60"] },
    { "test": "$$sin^{-1}(1)$$", "answers": ["90"] },
    { "test": "$$cos^{-1}(0)$$", "answers": ["90"] },
    { "test": "$$cos^{-1}({1 \\over 2})$$", "answers": ["60"] },
    { "test": "$$cos^{-1}({1 \\over \\sqrt 2})$$", "answers": ["45"] },
    { "test": "$$cos^{-1}({\\sqrt 3 \\over 2})$$", "answers": ["30"] },
    { "test": "$$cos^{-1}(1)$$", "answers": ["0"] }
  ]
};
